config/routes.rb
Rails.application.routes.draw do
  root 'books#landing'
  resources :books, only: [:create, :index, :new, :destroy, :show, :edit, :update]

  match '*unmatched', to: 'application#not_found', via: :all
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base
    def not_found
        render 'errors/not_found', status: :not_found
    end
  end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all

        if params[:search].present?
            search_term = params[:search].downcase
            @books = @books.where('LOWER(title) LIKE ? OR LOWER(author) LIKE ?', "%#{search_term}%", "%#{search_term}%")
        end

        @books_unfinished = @books.where(finished: false)
        @books_finished = @books.where(finished: true)
        
        @books_unfinished_sort_by_created = @books_unfinished.order(created_at: :desc)
        @books_finished_sort_by_finished_date = @books_finished.order(finishedDate: :desc)
        @books_finished_sort_by_stars = @books_finished.order(stars: :desc)

        @sort_by_stars = params[:sort_by] == 'stars'
    end
 
    def landing
        @books = Book.all
    end

    def new
        @book = Book.new()
    end
 
    def create
        @book = Book.new(book_params)
        @book.finishedDate = Date.today if @book.finished
        if @book.save
            redirect_to books_path
        else
            render :new
        end
    end

    def show
        @book = Book.find(params[:id])
    end

    def edit
        @book = Book.find(params[:id])
      end
    
      def update
        @book = Book.find(params[:id])
        
        if !@book.finished && book_params[:finished] == "1"
          @book.finishedDate = Date.today
        end
      
        if @book.update(book_params)
          redirect_to @book
        else
          render :edit
        end
      end

    def destroy
        Book.find(params[:id]).destroy
        redirect_to books_path
    end
 
    private
 
    def book_params
        params.require(:book).permit(:title, :author, :stars, :finished, :finishedDate, :thoughts)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
    def index
        @entries = Entry.all
    end
 
    def new
        @entry = Entry.new()
    end
 
    def create
        @entry = Entry.new(entry_params)
        if @entry.save
            redirect_to root_url
        else
            render :new
        end
    end

    def destroy
        Entry.find(params[:id]).destroy
        redirect_to root_url
    end
 
    private
 
    def entry_params
        params.require(:entry).permit(:name, :link)
    end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/books/edit.html.erb
<h1 class="text-center mb-4 title-fade-in">Edit Book</h1>

<div class="container show-container">
  <div class="show-book-content">
    <%= form_with(model: @book, local: true) do |form| %>
        <div class="book-form-spacing">
            <div>
                <div class="form-group">
                    <%= form.label :title, class: 'form-label-edit' %>
                    <%= form.text_field :title, class: 'form-control' %>
                </div>

                <div class="form-group">
                    <%= form.label :author, class: 'form-label-edit' %>
                    <%= form.text_field :author, class: 'form-control' %>
                </div>

                <div class="form-group form-control-checkbox">
                    <%= form.label :finished, class: 'form-label-edit' %>
                    <%= form.check_box :finished, data: { toggle: "true" } %>
                </div>

                <div class="form-group toggle-fields" style="display: none;">
                    <%= form.label :stars, class: 'form-label-edit' %>
                    <%= form.number_field :stars, class: "form-control", min: 0, max: 5, step: 0.5 %>
                </div>

                <div class="form-group toggle-fields" style="display: none;">
                    <%= form.label :thoughts, class: 'form-label-edit' %>
                    <%= form.text_area :thoughts, rows: 6, class: 'form-control thoughts-input' %>
                </div>

            </div>
            <div>
                <div class="action-buttons">
                    <%= link_to 'Cancel', book_path(@book), class: 'btn btn-secondary' %>
                    <%= form.submit 'Save changes', class: 'btn btn-custom' %>
                </div>
            </div>
        </div>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<h1 class="text-center mb-4 title-fade-in">My Books</h1>
<div class="container fade-in-animation">
  <div class="row mb-4">
    <div class="col-12 d-flex justify-content-center">

      <%= form_with url: books_path, method: :get, local: true, class: "d-inline-flex align-items-center" do %>
        <label>
        <div class="input-group">
          <%= text_field_tag :search, params[:search], placeholder: "Search by title or author", class: "form-control" %>
          <div class="input-group-append">
            <%= button_tag type: "submit", class: "btn btn-primary index-search-btn" do %>
              Search
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>



  <div class="row">
    <% if @books.empty? %>
      <div class="empty-container col-12 text-center">
        <h2 class="empty-messsage">So empty... </h2>
        <%= link_to "Add a book", new_book_path, class: "empty-button" %>
      </div>
    <% else %>

      <% if @books_unfinished.any? && @books_finished.any? %>
        <div class="col-12">
          <h2>What you're reading...</h2>
        </div>
      <% end %>

      <% @books_unfinished_sort_by_created.each do |book| %>
        <div class="col-md-3 mb-4">
          <div class="book" data-book-id="<%= book.id %>">
            <div class="book-content">
              <div>
                <h2 class="book-title"><%= book.title %></h2>
                <h3 class="book-author"><%= book.author %></h3>
                <p class="book-started-date">Started on <%= book.created_at.strftime('%Y-%m-%d') %></p>
              </div>
              <div class="book-buttons-container">
                <%= button_to book, method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "Are you sure you want to delete this book?" } do %>
                  <%= image_tag 'bin.png', alt: 'Delete', class: 'delete-icon' %>
                <% end %>

                <div class="open-link-container">
                  <%= link_to "Open >", book_path(book), class: "open-link" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>

      <% if @books_finished.any? %>
        <div class="col-12">
          <div class="d-flex justify-content-between align-items-center">
            <h2>What you've read...</h2>
              <%= form_with url: books_path, method: :get, local: true, class: "d-inline-flex align-items-center" do %>
                <div class="form-check form-switch">
                  <%= check_box_tag :sort_by, 'stars', @sort_by_stars, id: 'sort_by_stars', class: "form-check-input", onchange: 'this.form.submit();' %>
                  <label class="form-check-label" for="sort_by_stars">Sort by stars</label>
                </div>
              <% end %>
          </div>
        </div>

        <% books_to_display = @sort_by_stars ? @books_finished_sort_by_stars : @books_finished_sort_by_finished_date %>

        <% books_to_display.each do |book| %>
          <div class="col-md-3 mb-4">
            <div class="book" data-book-id="<%= book.id %>">
              <div class="book-content">
                <div>
                  <h2 class="book-title"><%= book.title %></h2>
                  <h3 class="book-author"><%= book.author %></h3>
                  <p class="book-finished-date">Finished on <%= book.finishedDate %></p>
                  <h3 class="book-stars"><%= book.stars %> stars</h3>
                  <% if book.thoughts.present? %>
                    <div class="book-thoughts">
                      <%= image_tag 'speech-bubble.webp', alt: 'Thoughts icon', class: 'speech-bubble-icon' %>
                    </div>
                  <% end %>
                </div>
                <div class="book-buttons-container">
                  <%= button_to book, method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "Are you sure you want to delete this book?" } do %>
                    <%= image_tag 'bin.png', alt: 'Delete', class: 'delete-icon' %>
                  <% end %>

                  <div class="open-link-container">
                    <%= link_to "Open >", book_path(book), class: "open-link" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>

      <% end %>
    <% end %>
  </div>
</div>

app/views/books/landing.html.erb
<h1 class="text-center mb-4 title-fade-in">Welcome to Bookr</h1>

<div class="landing-content">
    <h2 class="text-center mb-4"><%= @books.length %> books added!</h2>

    <div class="landing-img-container">
    <% @books.each do |book| %>
        <%= link_to book_path(book) do %>
          <%= image_tag 'bookr.png', alt: "Bookr logo", class: "landing-img" %>
        <% end %>
      <% end %>
      
    </div>

    <h2 class="text-center">Reading history</h2>

    <div class="landing-graph-section" >
        <div class="landing-graph-container" >
         <%= line_chart Book.group_by_month(:finishedDate).count, colors: ["#E42535", "#fff"],  download: true, xtitle: "Month", ytitle: "Books Finished" %>
        </div>
    </div>
    <h2 class="text-center mb-4">Keep it up!</h2>
</div>

app/views/books/new.html.erb
<h1 class="text-center title-fade-in">New Book</h1>

<div class="new-entry-container">
  <div class="new-entry-img-container">
    <%= image_tag 'bookr.png', class: "new-entry-img"%>
  </div>

  <%= form_with(model: @book, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= form.label :author, class: "form-label" %>
      <%= form.text_field :author, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= form.label :finished, class: "form-label" %>
      <%= form.check_box :finished, class: "form-control-checkbox", data: { toggle: "true" } %>
    </div>

    <div class="form-group toggle-fields" style="display:none;">
      <%= form.label :stars, class: "form-label" %>
      <%= form.number_field :stars, class: "form-control", min: 0, max: 5, step: 0.5 %>
    </div>

    <div class="form-group toggle-fields" style="display:none;">
      <%= form.label :thoughts, class: "form-label" %>
      <%= form.text_area :thoughts, rows:6, class: "form-control thoughts-input" %>
    </div>

    <div class="action-buttons">
      <div class="back-link">
        <%= link_to "< Back", books_path, class: "btn btn-secondary" %>
      </div>

      <div class="form-group">
        <%= form.submit "Create Book", class: "btn btn-primary btn-custom" %>
      </div>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<h1 class="text-center mb-4 title-fade-in">My Books</h1>
<div class="container show-container">

<div class="show-book-content book-form-spacing">
    <div>
        <div class="show-book-back-container">
        <%= link_to '< Back', books_path, class: 'show-book-back' %>
        </div>
        <h1 class="show-book-title"><%= @book.title %></h1>
        <h2 class="show-book-author"><%= @book.author %></h2>
        <br/>
        <% if @book.finished %>
            <p class="show-book-finished-date">Finished on: <%= @book.finishedDate %></p>
            <h3 class="show-book-stars"><%= @book.stars %> stars</h3>
            <h3 class="show-book-label">Your thoughts</h3>
            <p class="show-book-thoughts"><%= @book.thoughts %></p>
        <% else %>
            <p class="show-book-started-date">Started on: <%= @book.created_at.strftime('%Y-%m-%d') %></p>
        <% end %>
    </div>
    <div class="show-book-buttons-container">
        <%= button_to @book, method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "Are you sure you want to delete this book?" } do %>
            <%= image_tag 'bin.png', alt: 'Delete', class: 'show-delete-icon' %>
        <% end %>
        <div class="show-book-edit-container">
            <%= link_to 'Edit', edit_book_path(@book), class: 'show-book-edit' %>
        </div>
    </div>
</div>
</div>

app/views/entries/index.html.erb
<h1 class="text-center mb-4">Your Entries</h1>
<div class="container">
  <div class="row">
    <% @entries.each do |entry| %>
      <div class="col-md-3 mb-4">
        <div class="book">
          <div class="book-content">
            <h5 class="book-title"><%= entry.name %></h5>
            <p class="book-link">
              <a href="<%= entry.link %>">View Link</a>
            </p>
            <%= button_to "Delete", entry, method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "Are you sure you want to delete this Project?" } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<div class="new-entry-container">
  <%= form_with(model: @entry, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :link, class: "form-label" %>
      <%= form.text_field :link, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.submit "Create Entry", class: "btn btn-primary btn-custom" %>
    </div>
  <% end %>

  <div class="back-link">
    <%= link_to "Back to home", root_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
 <head>
   <title>Bookr</title>
   <meta name="viewport" content="width=device-width,initial-scale=1">

   <%= csrf_meta_tags %>
   <%= csp_meta_tag %>

   <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="icon" href="<%= asset_path 'bookr-white.png' %>">

 </head>

 <body>
   <%= render '/shared/navbar' %>
   <main>
     <%= yield %>
  </main>
 </body>

 
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-custom">
<div class="container">
  <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("bookr-white.png", alt: "Bookr Logo", class: "logo-class") %>
      <span>Bookr</span>
    <% end %>
    <ul class="navbar-nav navbar-link ml-auto">
        <li class="nav-item">
         <%= link_to "My Books", books_path, class: "nav-link" %>
        </li> 
        <li class="nav-item">
        <%= link_to "New Book", new_book_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Log Out", root_path, class: "nav-link" %>
        </li>
    </ul>
</div>
</nav>